apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: sample-app-demo
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: order-service
          image: docker.io/library/sample-java-app:k8s-demo
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "order"
            - name: SERVER_PORT
              value: "8080"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:8081"
            - name: INVENTORY_SERVICE_NAME
              value: "inventory-service"
            - name: OTEL_SERVICE_NAME
              value: "order-service"
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=lab,service.namespace=sample-app-demo,k8s.pod.name=$(K8S_POD_NAME),k8s.pod.uid=$(K8S_POD_UID),k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.deployment.name=order-service,k8s.cluster.name=downstream"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://suse-observability-otel-collector.suse-observability.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: sample-app-observability
                  key: otlp-headers
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: sample-app-demo
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8080
      targetPort: 8080
